### PR TITLE
Fix #960: Improve logging for sendPushMessageBatch

### LINKED ISSUE #960: Improve logging for sendPushMessageBatch
### Task specification

When sendPushMessageBatch is called, success is returned even though some messages failed. Log summary numbers from `PushMessageSendResult.PlatformResult`.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by jnpsk — APPROVED** [review]
looks ok

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
Please follow the logging guideline.

File: powerauth-push-server/src/main/java/com/wultra/push/controller/rest/PushMessageController.java [hunk 1]
```diff
@@ -126,7 +126,7 @@ public ObjectResponse<BasePushMessageSendResult> sendPushMessageBatch(@RequestBo
         final Mode mode = requestObject.getMode();
         final List<PushMessage> batch = requestObject.getBatch();
         final BasePushMessageSendResult result = pushMessageSenderService.sendPushMessage(appId, mode, batch);
-        logger.info("The sendPushMessageBatch request succeeded, application ID: {}", requestObject.getAppId());
+        logger.info("The sendPushMessageBatch request succeeded, application ID: {}, {}", requestObject.getAppId(), result);
```
Comment (zcgandcomp) [inline powerauth-push-server/src/main/java/com/wultra/push/controller/rest/PushMessageController.java]: We should start logging with:

  logger.info("action: {}, state: {}, applicationId: {}", "sendPushMessageBatch", "initiated", requestObject.getAppId());

And finish with:

  logger.info("action: {}, state: {}, result: {}", "sendPushMessageBatch", "succeeded", result );

I honestly have a doubts regarding the logging of the whole result object, but it is acceptable, as we want to log the job result, not excessive details and the object is reasonably small.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]

File: powerauth-push-server/src/main/java/com/wultra/push/controller/rest/PushMessageController.java (hunk 1 above)
Comment (banterCZ) [reply powerauth-push-server/src/main/java/com/wultra/push/controller/rest/PushMessageController.java]: Ok, I will change it to a new form. I am touching this because we may log _succeeded_, but the result is `(sent=0, failed=1, pending=0, total=1)`, which is not visible right now.

**Review by zcgandcomp — APPROVED** [review]
Ok, understand the need to log more relevant information. Let's do all changes in a structured way for better observability.
