### PR TITLE
Fix #884: clearing the cache of the push client works only on one node

### LINKED ISSUE #884: caching of push client is not sensitive for changes
Step to reproduce:
Create FCM config for an application.
Send push notifications for the registration of the application for the Android platform. (client is stored in cache)
Create APNS configuration for the application.
Send push notifications for the registration of the application for the iOS platform. (client is read from cache)

Expected result: 
The push notification is sent

Actual result:
No push is sent. An error in the log:
`Push message cannot be sent to APNS because APNS is not configured in push server`

### PR DESCRIPTION
**Pull request by banterCZ**
- limit expiration time

### CODE REVIEW

File: powerauth-push-server/src/main/java/io/getlime/push/configuration/StorageConfiguration.java [hunk 1]
```diff
@@ -16,25 +16,32 @@
...
 /**
- * Configuration class for in memory maps
+ * Configuration class for storage.
  *
  * @author Martin Tupy, martin.tupy.work@gmail.com
  */
 @Configuration
-public class StorageMapConfiguration {
+@Slf4j
+public class StorageConfiguration {
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/configuration/StorageConfiguration.java:35]: I would rather call it `PushServiceConfiguration` but there already is such a class, which should be named `PushServiceConfigurationProperties`. Anyway, let's postpone to another PR.

File: powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/ItemStorage.java [hunk 2]
```diff
@@ -37,18 +37,6 @@ public interface ItemStorageMap<K,V> {
      */
     void put(K key, V value);
 
-    /**
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/ItemStorage.java:40]: Not used at all.

File: powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/ItemStorage.java [hunk 3]
```diff
@@ -21,7 +21,7 @@
  * @param <K> Key class for item storage.
  * @param <V> Value class for item storage.
  */
-public interface ItemStorageMap<K,V> {
+public interface ItemStorage<K,V> {
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/ItemStorage.java:24]: The interface should not say much about the underlying implementation. Anyway, we should switch to `Cache` later on instead of the custom one, to enable such a feature as `#get(K key, Function<K, V> mappingFunction)`.

File: powerauth-push-server/src/main/resources/application.properties [hunk 4]
```diff
@@ -53,6 +53,8 @@ powerauth.push.service.registration.multipleActivations.enabled=false
 powerauth.push.service.registration.retry.backoff=100
 powerauth.push.service.registration.retry.maxAttempts=2
 
+powerauth.push.service.clients.cache.expireAfterWrite=24h
```
Comment (banterCZ) [inline powerauth-push-server/src/main/resources/application.properties:56]: @zcgandcomp What is the reasonable default?

File: powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/CampaignMessageStorage.java [hunk 5]
```diff
@@ -28,7 +28,7 @@
  *
  * @author Petr Dvorak, petr@wultra.com
  */
-public class CampaignMessageStorageMap implements ItemStorageMap<Long, PushCampaignEntity> {
+public class CampaignMessageStorage implements ItemStorage<Long, PushCampaignEntity> {
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/CampaignMessageStorage.java:31]: 🤔 Should we set expiration even for campaigns?

Comment (banterCZ) [reply powerauth-push-server/src/main/java/io/getlime/push/service/batch/storage/CampaignMessageStorage.java:31]: Ok, let's ignore expiration here because the campaign is cached for a single run only.

File: powerauth-push-server/src/main/resources/application.properties (hunk 4 above)
Comment (banterCZ) [reply powerauth-push-server/src/main/resources/application.properties:56]: It seems that 24 hours is too long, but 5 minutes is too short because initializing the client is quite heavy. Let's consider some smart reloadable cache.

File: docs/Push-Server-Database.md [hunk 6]
```diff
@@ -92,25 +92,29 @@ CREATE TABLE push_app_credentials (
     ios_bundle VARCHAR(255),
     ios_environment VARCHAR(32),
     android_private_key BYTEA,
-    android_project_id VARCHAR(255)
+    android_project_id VARCHAR(255),
```
Comment (banterCZ) [inline docs/Push-Server-Database.md:95]: Let's remove SQL completely in a different PR. This update just makes it consistent.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
few issues

File: powerauth-push-server/src/main/java/io/getlime/push/service/AppRelatedPushClientCacheLoader.java [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+
+        final LocalDateTime lastUpdatedInDb = credentials.getTimestampLastUpdated();
+        final LocalDateTime lastUpdatedInCache = oldValue.getAppCredentials().getTimestampLastUpdated();
+        if (Objects.equals(lastUpdatedInCache, lastUpdatedInDb)) {
+            logger.debug("LastUpdated is same for app: {}", key);
+            return oldValue;
+        }
+
+        logger.debug("LastUpdated differs for app: {}", key);
+        return load(key);
```
[the remark this answers is not in the document]
Comment (banterCZ) [reply powerauth-push-server/src/main/java/io/getlime/push/service/AppRelatedPushClientCacheLoader.java:68]: A good point. Normally, it should be cached by the entity manager, but since it is loaded async, it will load the record twice.

**Review by jnpsk — APPROVED** [review]
looks good, nice solution

File: powerauth-push-server/src/main/java/io/getlime/push/repository/model/AppCredentialsEntity.java [hunk 8]
```diff
@@ -112,4 +113,10 @@ public class AppCredentialsEntity implements Serializable {
     @Column(name = "hms_client_secret")
     private String hmsClientSecret;
 
+    @Column(name = "timestamp_created", nullable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
```
[the remark this answers is not in the document]
Comment (banterCZ) [reply powerauth-push-server/src/main/java/io/getlime/push/repository/model/AppCredentialsEntity.java:116]: This is a hint for h2-generated db in tests.

File: powerauth-push-server/src/main/java/io/getlime/push/service/AppRelatedPushClientCacheLoader.java [hunk 9]
```diff
@@ -65,22 +65,23 @@ public AppRelatedPushClient reload(final String appId, final AppRelatedPushClien
...
     }
 
     @Override
-    public AppRelatedPushClient load(final String key) throws Exception {
-        final AppCredentialsEntity credentials = appCredentialsRepository.findFirstByAppId(key).orElse(null);
+    public AppRelatedPushClient load(final String appId) throws Exception {
+        final AppCredentialsEntity credentials = appCredentialsRepository.findFirstByAppId(appId).orElse(null);
         if (credentials == null) {
-            logger.debug("AppCredentials does not exist for app: {}", key);
+            logger.debug("AppCredentials does not exist for app: {}", appId);
```
Comment (zcgandcomp) [inline powerauth-push-server/src/main/java/io/getlime/push/service/AppRelatedPushClientCacheLoader.java:75]: I suggest raising it as a warning, as this might not be a breaking problem, but very probably it can be. Same for reload.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
Small change for logging and we are clear to go.

**Review by zcgandcomp — APPROVED** [review]
Looks OK
