### PR TITLE
Fix #841: Add warning when push notification cannot be sent

### LINKED ISSUE #841: Add warning when push notification cannot be sent due to an invalid userId or userId+activationId combination
Currently if `userId` or combination of `userId` and `activationId` doesn't have any activation to send push notification to, we do not send the push, but push server doesn't provide any warning.

Add to log WARN message that no device was found to send the push notification to.

(Alternatively we can raise an exception if the combination is not valid - TBD)

### PR DESCRIPTION
**Pull request by banterCZ**
Add warning when push notification cannot be sent due to an invalid userId or userId+activationId combination

### CODE REVIEW

File: powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java [hunk 1]
```diff
@@ -261,16 +261,24 @@ private AppCredentialsEntity getAppCredentials(String appId) throws PushServerEx
...
         if (activationId != null) { // in case the message should go to the specific device
-            return pushDeviceRepository.findByUserIdAndAppCredentialsIdAndActivationId(userId, id, activationId);
+            devices = pushDeviceRepository.findByUserIdAndAppCredentialsIdAndActivationId(userId, appCredentialsId, activationId);
         } else {
-            return pushDeviceRepository.findByUserIdAndAppCredentialsId(userId, id);
+            devices = pushDeviceRepository.findByUserIdAndAppCredentialsId(userId, appCredentialsId);
+        }
+
+        if (devices.isEmpty()) {
+            throw new PushServerException("No device found for userId=%s, appCredentialsId=%s, activationId=%s".formatted(userId, appCredentialsId, activationId));
```
Comment (zcgandcomp) [inline powerauth-push-server/src/main/java/io/getlime/push/service/PushMessageSenderService.java:278]: For now please just log the warning. Thank you

**Review by zcgandcomp — CHANGES_REQUESTED** [review]

**Review by zcgandcomp — APPROVED** [review]
ok, nice. Let's followup if the exception is better later on.
