### PR TITLE
Fix #910: Make CA certificate loading fail early

### LINKED ISSUE #910: Make CA certificate loading fail early
We faced several regression bugs while loading the certificates. Make loading eager to fail early.

A follow-up to #909

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java [hunk 1]
```diff
@@ -30,19 +31,17 @@
...
+ * Service for working with CA Certificates.
  *
  * @author Petr Dvorak, petr@wultra.com
  */
 @Service
-@AllArgsConstructor
+@RequiredArgsConstructor
 @Slf4j
-public class CaCertUtil {
+public class CaCertificateService {
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java:44]: Misleading, it is not a util class.

File: powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java [hunk 2]
```diff
@@ -59,12 +58,21 @@ public class CaCertUtil {
...
 
+    private List<X509Certificate> allCertificates;
+
     /**
      * Obtain all registered CA certificates.
      * @return All registered CA certificates.
      */
     public X509Certificate[] allCerts() {
-        // Prepare result list
+        return allCertificates.toArray(X509Certificate[]::new);
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java:68]: Besides early failure, we get the performance improvement to load it just once.

**Review by romanstrobl — APPROVED** [review]
Nice improvement!

File: powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java [hunk 3]
```diff
@@ -59,12 +58,21 @@ public class CaCertUtil {
...
+    }
+
+    /**
+     * Load the locally stored CA certificates required by Apple for APNs.
+     */
+    @PostConstruct
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java:74]: @zcgandcomp This may affect startup time, but the benefit is, that it is loaded once per push-server instance and fails early if any error. This used to be called per APNS client and failed when called.

File: powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java [hunk 4]
```diff
@@ -83,29 +94,35 @@ public X509Certificate[] allCerts() {
...
-                    final String certString = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
-                    final X509Certificate cert = certificateFromPem(certString);
-                    result.add(cert);
-                }
-            } catch (CertificateException | IOException e) {
-                logger.error("Certificate error: {}", e.getMessage(), e);
+        result.addAll(loadEmbeddedCertificate());
+
+        allCertificates = result;
+        logger.debug("#loadAllCertificates took {} ms", System.currentTimeMillis() - startTimestamp);
```
Comment (banterCZ) [inline powerauth-push-server/src/main/java/io/getlime/push/service/CaCertificateService.java]:
```log
#loadAllCertificates took 24 ms
```

**Comment by banterCZ** [comment]
As confirmed with @zcgandcomp at technical-grooming, this change does not heavily affect the start time.
