### PR TITLE
Fix #602: Make PushServerTests#sendCampaignTest independent

### LINKED ISSUE #602: Make PushServerTests#sendCampaignTest independent
Test case `sendCampaignTest` at `PushServerTests` is not independent and fails when running only that one.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-push-server/src/test/java/io/getlime/push/tests/PushServerTests.java [hunk 1]
```diff
@@ -296,27 +283,28 @@ public void getListOfUsersFromCampaignTest() throws Exception {
...
         boolean actual = pushServerClient.sendTestCampaign(1L, "Test_User");
         assertTrue(actual);
     }
 
     @Test
-    public void sendCampaignTest() throws Exception {
-        boolean actual = pushServerClient.sendCampaign(1L);
-        assertTrue(actual);
+    void sendCampaignTest() throws Exception {
+        createCampaign();
```
Comment (banterCZ) [inline powerauth-push-server/src/test/java/io/getlime/push/tests/PushServerTests.java:301]: ℹ️ The main change.

**Review by romanstrobl — APPROVED** [review]
Looks OK.
